### ISSUE TITLE
UI invitation projet vide 

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform#199]
![chrome-capture - 2022-04-22T153941 301](https://user-images.githubusercontent.com/32667664/164725864-4ae91200-a9c8-44be-8d69-4fe3ed2dc9a0.jpg)

**Comment by NicolasRichel** [comment]
@GabBimdata
J'ai testé et je n'arrive pas à reproduire ce problème (ni sur **staging** ni sur **next**).
Je pense qu'il s'agit une fois de plus d'une "fuite de styles" dont l'origine est encore difficile à déterminer...
ça ressemble beaucoup au problème que tu avais avec les boutons de areas sur le viewer...
