### ISSUE TITLE
Message plus explicite à l'invitation d'un user déjà présent dans le projet

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform#220]
![image](https://user-images.githubusercontent.com/32667664/168813948-5f89b259-2df6-4003-98ae-2dc9c594b1e1.png)

Hugo me dit dans l'oreille qu'on a déjà de quoi afficher un message de type "Cet utilisateur est déjà présent dans le projet" en lieu et place du message trop général qu'on affiche aujourd'hui (cf. image ci-dessus).

**Comment by Amoki** [comment]
Dans ce cas, l'API renvoie une 400 avec le json `{"already_exists":"This user is already a member of this project"}`
Regarder la clé `already_exists` est suffisant imho.
Pareil dans le cas d'une invitation dans un espace
