### ISSUE TITLE
Bug panneau de gestion admin/users espace

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform#234]
![image](https://user-images.githubusercontent.com/32667664/170962816-cfc8b540-b084-4acd-af68-afc29832f645.png)

Je n'ai plus rien dans la listes admin et user dans le panneau de gestion d'espace. (vu avec les backeux, l'API réagit bien)

**Comment by NicolasRichel** [comment]
Je suis tombé sur ce bug en travaillant sur d'autres issues.
J'ai pu identifier l'origine du problème qui est que l'API nous renvoie `null` dans le champs `cloud_role` des objets **user** retournés par un call à `GET /cloud/{cloud_pk}/user`.
En effet on se sert de ce champ pour séparer la liste des admins de celle des simple utilisateurs.
Ce problème n'est pas présent sur la vue projet car les objets **user** renvoyées par `GET /cloud/{cloud_pk}/project/{project_pk}/user` on a bien un champ `role` qui à la valeur attendue. 

@Amoki @amineau on peut regarder ensemble quand vous aurez un moment. :)
