### ISSUE TITLE
TAG - problème lorsque je souhaite retirer un tag

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform#238]
![image](https://user-images.githubusercontent.com/32667664/172396651-4a9793bc-0607-4ca9-94dc-c4e76138e9ac.png)

En allant un peu rapidement (je voulais rectifier un tag) je suis tombé dans un "trou".

**Comment by pvilalta** [comment]
this issue has been fixed within the lastest commit on feature/tag PR
