### ISSUE TITLE
Refresh la liste des users (espace et projet)

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform#241]
![image](https://user-images.githubusercontent.com/32667664/172639008-1d9b6cc7-0c54-49f4-87df-227385f6af4e.png)

Refresh la liste au bout de 2 secondes.

**Comment by Amoki** [comment]
When using SSO with forks, developers may decide to automatically accept invitations.
In this case, the acceptance is asynchronous and may take 1 or 2 seconds.
Refreshing automatically the user list 2 second after the request could be great
