### ISSUE TITLE
Problème bandeau à la réactivation du paiement

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform#254]
![image](https://user-images.githubusercontent.com/32667664/177573609-021293fc-dd80-489c-b961-b67c83fcaeb0.png)

Je viens de réactiver mon abonnement mais j'ai toujours le bandeau qui s'affiche :/

**Comment by NicolasRichel** [comment]
@GabBimdata 
Yesterday I pushed a fix for this issue: #251 
I think it could have fixed this one too.
Could you test it again (on staging) please ?
