### ISSUE TITLE
Versioning: no visual indication when deleting a version 

### ISSUE THREAD

**Issue by RomainMou** [bimdata/platform#260]
On staging, when I delete a version, there is no indication. It's working, I just need to wait but I don't know it. That's a little bit confusing.

![version-delete-modals](https://user-images.githubusercontent.com/58464216/179788445-a584ea41-4834-4de1-bbc1-4e51d9a4dc84.gif)

**Comment by Amoki** [comment]
Only append on models because there are many properties to delete. We may want to suggest the deletion worked so the user is not blocked as we do when we delete projects.
