### ISSUE TITLE
BCF - side panel blanc et vide 

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform#282]
![image](https://user-images.githubusercontent.com/32667664/189061342-72bd9d52-6e14-4470-8235-d6088e60ef32.png)

Je n'arrive pas à reproduire systématiquement le problème mais c'est très régulièrement que je me retrouve à devoir refresh la page pour pouvoir accède au side panel :/

**Comment by NicolasRichel** [comment]
@GabBimdata tu as pu tester si le bug apparaît toujours ?
Si ce n'est pas le cas je close l'issue. :)
