### ISSUE TITLE
Problème nom long à la suppression des groupes utilisateurs

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform#345]
![image](https://user-images.githubusercontent.com/32667664/212772887-3f25fc14-b7c2-4efc-a727-5cf176999e35.png)

**Comment by pvilalta** [comment]
it's fixed with the user group import PR 

![Screenshot 2023-01-17 at 09 03 25](https://user-images.githubusercontent.com/64323277/212845557-894c0b97-f457-45ae-90ee-7d2cd8840c09.png)
