### ISSUE TITLE
Style leeks to the viewer

### ISSUE THREAD

**Issue by Kurtil** [bimdata/platform#62]
The buttons are really small when the viewer is open on the platform and this behaviour does not occur in development. It seems that some style of the platform leeks.

<img width="692" alt="Screenshot 2021-07-07 at 10 37 12" src="https://user-images.githubusercontent.com/22523482/124727783-4fb99d00-df0f-11eb-906e-a80ece8a9002.png">

Should be like this:
<img width="502" alt="Screenshot 2021-07-07 at 10 38 30" src="https://user-images.githubusercontent.com/22523482/124727961-7b3c8780-df0f-11eb-97a1-d65b656a2a43.png">

**Comment by Kurtil** [comment]
Related to this viewer issue https://github.com/bimdata/viewer/issues/558

**Comment by NicolasRichel** [comment]
OK, I'll investigate, but for now I am not able to reproduce it locally.
Seems that it's a "non deterministic" bug..

If you encounter this behavior again, could you please take a screenshot of your devtools, more specifically the stylesheets panel with the styles of one of the buttons.

This is what I can observe currently:

![Screenshot from 2021-07-08 09-41-29](https://user-images.githubusercontent.com/22519383/124882629-e1d5aa00-dfd0-11eb-8854-47de26085486.png)

**Comment by NicolasRichel** [comment]
It seems that the issue can be reproduced by opening the 2D engine in a new window.

Unfortunatetely, I'm still not able to reproduce the problem.. :(
(On both local and staging environment)

@Kurtil could we find a moment to have a look at this together ?

**Comment by NicolasRichel** [comment]
=> Self fixed. :)
